Switch MongoDB to Prisma and Clean Up Some Bad Architectures
winhacks/2024-bot pull request #1
Opened 2024-01-06 02:30 UTC by kilbouri

Dude I don't even want to write a description...

@BorhanSaflo and I switched the bot over to use Prisma and SQLite instead a MongoDB cluster for persistence. We also found some "wtf" architectural decisions that we fixed as well.

2024-01-06 02:32 UTC, jere-mie requested changes

2024-01-06 02:32 UTC, jere-mie commented on README.md
>  # WinHacks 2022 Discord Bot
Can we change this to 2024

2024-01-06 02:39 UTC, kilbouri commented on README.md
>  # WinHacks 2022 Discord Bot
Done

2024-01-11 16:44 UTC, jere-mie approved these changes
LGTM

2024-01-11 16:44 UTC, merged